"""add user_id to tasks

Revision ID: 68af4e481152
Revises: 
Create Date: 2026-08-10 19:15:21.791283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68af4e481152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usertasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertasks', type_='foreignkey')
    op.drop_column('usertasks', 'user_id')
    # ### end Alembic commands ###
